[[deprecations-and-additions]]
= Deprecations and additions
:description: This chapter lists all the features that have been removed, deprecated, added or extended in the recent versions of APOC.

This chapter lists all the features that have been removed, deprecated, added or extended in the recent versions of APOC.

[[apoc-deprecations-additions-removals-5.0]]
== Version 5.0

=== Deprecated procedures and functions

[cols="2", options="header"]
|===
| Feature
| Details
a|
label:function[]
label:deprecated[]
[source, cypher, role="noheader"]
----
RETURN apoc.create.uuid()
----
a|
Replaced by Neo4j Function randomUUID():
[source, cypher, role="noheader"]
----
RETURN randomUUID()
----

a|
label:procedure[]
label:deprecated[]
[source, cypher, role="noheader"]
----
CALL apoc.create.uuids($count)
----
a|
Replaced by Neo4j Function randomUUID():
[source, cypher, role="noheader"]
----
UNWIND range(0,$count) AS row RETURN row, randomUUID() AS uuid
----

|===

=== Removed procedures and functions

[cols="2", options="header"]
|===
| Feature
| Details

a|
label:procedure[]
label:removed[]
[source, cypher, role="noheader"]
----
apoc.algo.dijkstraWithDefaultWeight(startNode, endNode, 'KNOWS', 'distance', 10) YIELD path, weight
----
a|
Use the following instead:
[source, cypher, role="noheader"]
----
apoc.algo.dijkstra(startNode, endNode, 'KNOWS', 'distance', defaultValue, numberOfWantedResults) YIELD path, weight
----

a|
label:function[]
label:removed[]
[source, cypher, role="noheader"]
----
apoc.date.parseAsZonedDateTime('2012-12-23 23:59:59','yyyy-MM-dd HH:mm:ss', 'UTC-hour-offset')
----
a|
Replaced by:
[source, cypher, role="noheader"]
----
apoc.temporal.toZonedTemporal('2012-12-23 23:59:59','yyyy-MM-dd HH:mm:ss', 'UTC-hour-offset')
----

a|
label:function[]
label:removed[]
[source, cypher, role="noheader"]
----
apoc.coll.reverse(coll)
----
a|
Replaced in Cypher with:
[source, cypher, role="noheader"]
----
WITH [4923,'abc',521, null, 487] AS ids
RETURN reverse(ids)
----

a|
label:procedure[]
label:removed[]
[source, cypher, role="noheader"]
----
apoc.export.cypherAll(file,config)
----
a|
Replaced by:
[source, cypher, role="noheader"]
----
apoc.export.cypher.all(file,config)
----

a|
label:procedure[]
label:removed[]
[source, cypher, role="noheader"]
----
apoc.export.cypherData(nodes,rels,file,config)
----
a|
Replaced by:
[source, cypher, role="noheader"]
----
apoc.export.cypher.data(nodes,rels,file,config)
----

a|
label:procedure[]
label:removed[]
[source, cypher, role="noheader"]
----
apoc.export.cypherGraph(graph,file,config)
----
a|
Replaced by:
[source, cypher, role="noheader"]
----
apoc.export.cypher.graph(graph,file,config)
----

a|
label:procedure[]
label:removed[]
[source, cypher, role="noheader"]
----
apoc.export.cypherQuery(query,file,config)
----
a|
Replaced by:
[source, cypher, role="noheader"]
----
apoc.export.cypher.query(query,file,config)
----

a|
label:function[]
label:removed[]
[source, cypher, role="noheader"]
----
apoc.meta.type(value)
----
a|
Replaced by:
[source, cypher, role="noheader"]
----
apoc.meta.cypher.type(value)
----

a|
label:function[]
label:removed[]
[source, cypher, role="noheader"]
----
apoc.meta.types(node-relationship-map)
----
a|
Replaced by:
[source, cypher, role="noheader"]
----
apoc.meta.cypher.types(node-relationship-map)
----

a|
label:function[]
label:removed[]
[source, cypher, role="noheader"]
----
apoc.meta.isType(value,type)
----
a|
Replaced by:
[source, cypher, role="noheader"]
----
apoc.meta.cypher.isType(value,type)
----

a|
label:function[]
label:removed[]
[source, cypher, role="noheader"]
----
apoc.meta.typeName(value)
----
a|
Replaced by:
[source, cypher, role="noheader"]
----
apoc.meta.cypher.type(value)
----

a|
label:procedure[]
label:removed[]
[source, cypher, role="noheader"]
----
apoc.periodic.rock_n_roll_while('some cypher for knowing when to stop', 'some cypher for iteration', 'some cypher as action on each iteration', 10000) YIELD batches, total
----
a|
Partially replaced in Cypher with:
[source, cypher, role="noheader"]
----
CALL {} IN TRANSACTIONS OF n ROWS
----

a|
label:procedure[]
label:removed[]
[source, cypher, role="noheader"]
----
apoc.periodic.rock_n_roll('some cypher for iteration', 'some cypher as action on each iteration', 10000) YIELD batches, total
----
a|
Replaced in Cypher with:
[source, cypher, role="noheader"]
----
CALL {} IN TRANSACTIONS OF n ROWS
----

a|
label:procedure[]
label:removed[]
[source, cypher, role="noheader"]
----
apoc.create.vPattern({_labels:['LabelA'],key:value},'KNOWS',{key:value,...}, {_labels:['LabelB'],key:value}) returns a virtual pattern
----
a|
Replaced by:
[source, cypher, role="noheader"]
----
apoc.create.virtualPath(['LabelA'],{key:value},'KNOWS',{key:value,...},['LabelB'],{key:value})
----

a|
label:procedure[]
label:removed[]
[source, cypher, role="noheader"]
----
apoc.create.vPatternFull(['LabelA'],{key:value},'KNOWS',{key:value,...},['LabelB'],{key:value}) returns a virtual pattern
----
a|
Replaced by:
[source, cypher, role="noheader"]
----
apoc.create.virtualPath(['LabelA'],{key:value},'KNOWS',{key:value,...},['LabelB'],{key:value})
----

a|
label:procedure[]
label:removed[]
[source, cypher, role="noheader"]
----
apoc.xml.import(url, config)
----
a|
Replaced by:
[source, cypher, role="noheader"]
----
apoc.import.xml(file,config)
----

a|
label:procedure[]
label:removed[]
[source, cypher, role="noheader"]
----
apoc.refactor.cloneNodesWithRelationships([node1,node2,...])
----
a|
Use the following instead, and set withRelationships = true:
[source, cypher, role="noheader"]
----
apoc.refactor.cloneNodes(nodes, withRelationships, skipProperties)
----

a|
label:procedure[]
label:removed[]
[source, cypher, role="noheader"]
----
CALL apoc.text.phonetic(value) yield value
----
a|
Replaced by the function:
[source, cypher, role="noheader"]
----
RETURN apoc.text.phonetic(text) yield value
----

a|
label:procedure[]
label:removed[]
[source, cypher, role="noheader"]
----
CALL apoc.text.doubleMetaphone(value) yield value
----
a|
Replaced by the function:
[source, cypher, role="noheader"]
----
RETURN apoc.text.doubleMetaphone(text) yield value
----

a|
label:function[]
label:removed[]
[source, cypher, role="noheader"]
----
apoc.math.round(value,[prec],mode=[CEILING,FLOOR,UP,DOWN,HALF_EVEN,HALF_DOWN,HALF_UP,DOWN,UNNECESSARY])
----
a|
Replaced by the Neo4j round() function:
[source, cypher, role="noheader"]
----
RETURN round(3.141592, 3)
----

a|
label:procedure[]
label:removed[]
[source, cypher, role="noheader"]
----
apoc.warmup.run(loadProperties=false,loadDynamicProperties=false,loadIndexes=false)
----
a|
This procedure duplicated functionality of page cache warm up which is a part of the DBMS.

a|
label:function[]
label:removed[]
[source, cypher, role="noheader"]
----
apoc.cypher.runFirstColumn(statement, params, expectMultipleValues)
----
a|
Replaced by:
[source, cypher, role="noheader"]
----
apoc.cypher.runFirstColumnMany(statement, params)
----
[source, cypher, role="noheader"]
----
apoc.cypher.runFirstColumnSingle(statement, params)
----
|===

=== Removed Config Settings

[cols="2", options="header"]
|===
| Setting
| Details

a|
label:setting[]
label:removed[]
apoc.initializer.cypher - a cypher statement to be executed once the database is started
a|
This has been replaced by database-specific initializers. Use apoc.initializer.<database name> instead.
|===