////
This file is generated by DocsTest, so don't change it!
////

= apoc.load
:description: This section contains reference documentation for the apoc.load procedures.

[.procedures, opts=header, cols='5a,1a,1a']
|===
| Qualified Name | Type | Release
|xref::overview/apoc.load/apoc.load.json.adoc[apoc.load.json icon:book[]]

apoc.load.json('urlOrKeyOrBinary',path, config) YIELD value - import JSON as stream of values if the JSON was an array or a single value if it was a map
|label:procedure[]
|label:apoc-core[]
|xref::overview/apoc.load/apoc.load.jsonArray.adoc[apoc.load.jsonArray icon:book[]]

apoc.load.jsonArray('url') YIELD value - load array from JSON URL (e.g. web-api) to import JSON as stream of values
|label:procedure[]
|label:apoc-core[]
|xref::overview/apoc.load/apoc.load.jsonParams.adoc[apoc.load.jsonParams icon:book[]]

apoc.load.jsonParams('urlOrKeyOrBinary',{header:value},payload, config) YIELD value - load from JSON URL (e.g. web-api) while sending headers / payload to import JSON as stream of values if the JSON was an array or a single value if it was a map
|label:procedure[]
|label:apoc-core[]
|xref::overview/apoc.load/apoc.load.xml.adoc[apoc.load.xml icon:book[]]

apoc.load.xml('http://example.com/test.xml', 'xPath',config, false) YIELD value as doc CREATE (p:Person) SET p.name = doc.name - load from XML URL (e.g. web-api) to import XML as single nested map with attributes and _type, _text and _childrenx fields.
|label:procedure[]
|label:apoc-core[]
|===

