name: "Test gradle project"

inputs:
  project-name:
    description: "Name of gradle project to test"
    required: true
  java-version:
    description: "JDK to use"
    required: true

runs:
  using: "composite"
  steps:
    - uses: ./.github/actions/setup-jdk
      with:
        java-version: ${{inputs.java-version}}
    - uses: ./.github/actions/setup-gradle-cache
    - name: Run tests
      shell: bash
      run: ./gradlew ${{inputs.project-name}}:test --parallel
    - name: Archive test results
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: ${{inputs.project-name}}-${{inputs.java-version}}-test-results
        path: ${{inputs.project-name}}/build/reports/tests/test/
        if-no-files-found: ignore