name: Formats PR
on:
  repository_dispatch:
    types: [spotlessApply-command]

jobs:
  format:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Format and push changes to PR
        uses: ./.github/actions/gradle-command-on-pr
        with:
          gradle-command: spotlessApply
          SERVICE_ACCOUNT_PAT: ${{ secrets.SERVICE_ACCOUNT_PAT }}